apiVersion: v1
kind: Pod
metadata:
  name: nginx
    # labels:
    # type: webserver-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.11-alpine
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: worker  # kubectl get node worker --show-labels
