apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-env
  name: busy-env
spec:
  containers:
  - command:
    - env
    image: busybox
    name: busy-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
