apiVersion: v1
kind: Pod
metadata:
  labels:
    run: consumer2
  name: consumer2
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: consumer2
    resources: {}
    volumeMounts:
    - name: secret-volume
      mountPath: /var/app
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
