apiVersion: v1
kind: Pod
metadata:
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: consumer
    resources: {}
    envFrom:
    - secretRef:
        name: ext-service-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
