apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-sc
  name: nginx-sc
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    name: nginx-sc
    resources: {}
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
