apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: nginx-liveness-readiness
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
