apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: mysec
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: secret-vol
      readOnly: true
      mountPath: "/var/app"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
