apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-sec
  name: nginx-sec
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: mysec2
  containers:
  - image: nginx
    name: nginx-sec
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: secret-vol
      readOnly: true
      mountPath: "/etc/foo"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
