apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-from-env
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: anotherone
