apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-sec
  name: nginx-sec
spec:
  containers:
  - image: nginx
    name: nginx-sec
    ports:
    - containerPort: 80
    resources: {}
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysec2
          key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
