apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-pod-security
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    name: nginx-pod-security
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
