kind: ConfigMap
apiVersion: v1  
metadata:
  name: fast-car
  namespace: default
data:
  # will create files car.make, car.model, car.trim when mounted at a location
  car.make: Ford 
  car.model: Mustang
  car.trim: Shelby
