apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:  
  containers:  
  - image: mysql:5.5  
    name: mysql 
    env:  
    - name: MYSQL_ROOT_PASSWORD  
      valueFrom:  
        secretKeyRef:
          # you need to have a kubernetes secret mysql with a "password" key 
          name: mysql 
          key: password
    - name: ilike
      valueFrom:
        configMapKeyRef:
          name: colors  # or fast-car (car-configMap.yaml)
          key: favorite
    envFrom:
    - configMapRef:
        name: colors
    volumeMounts: 
      # mount path has a file whose name will be the key of the kubernetes secret 
      # (password)
      - mountPath: /mysqlpassword
        name: mysql-vol
      # will create files car.make, car.model, car.trim in /etc/cars
      - mountPath: /etc/cars
        name: car-vol
  volumes:
  - name: mysql-vol
    secret:
      secretName: mysql
  - name: car-vol
    configMap:
      defaultMode: 420 # u:read,g:write,o:-
      name: fast-car
