apiVersion: v1
kind: Pod  
metadata:  
  name: busybox  
  namespace: default  
spec:  
  containers:  
  - image: busybox  
    name: busy  
    command:  
      - sleep  
      - "3600"
    volumeMounts:  
    - name: test-volume
      mountPath: /vol-path
  volumes:  
  - name: test-volume
    persistentVolumeClaim:
      claimName: pvc-one 
