kind: PersistentVolumeClaim
apiVersion: v1  
metadata:  
  name: pvc-one  
spec:  
  accessModes:  
    - ReadWriteOnce  
  resources: 
    requests:
      storage: 200Mi
# Can be "manual" for statistically provisioned volumes: pv needs to have same class.
# Same with "standard": pv needs to have same class
# storageClassName: manual
