apiVersion: v1
kind: PersistentVolume
metadata:
  name: weblog-pv-volume
  labels:
    type: local
spec:
  # Makes volumes statically provisioned: volume has to have same class to be bound
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/weblog"  # needs to be created before unless type: FileOrCreate is added
