apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblog-pv-claim
spec:
  # Makes volumes statically provisioned: pvc has to have same class to bind volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
