apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-with-init
  name: nginx-with-init
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-vol
  initContainers:
  - image: busybox
    name: busy
    command: ["sh", "-c", "echo 'Test' > /work-dir/index.html"]
    volumeMounts:
    - mountPath: /work-dir
      name: shared-vol
  volumes:
  - name: shared-vol
    emptyDir: {}
