apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cj
spec:
  startingDeadlineSeconds: 17
  jobTemplate:
    metadata:
      name: hello-cj
    spec:
      activeDeadlineSeconds: 12
      template:
        metadata: {}
        spec:
          containers:
          - command:
            - sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: hello-cj
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
