# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# deployments.apps "nginxv1" was not valid:
# * spec.selector: Invalid value: {"matchLabels":{"app":"nginx","version":"v1"}}: field is immutable
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-10-30T13:15:57Z"
  generation: 2
  labels:
    app: nginx
    version: v1
  name: nginxv1
  namespace: ckad
  resourceVersion: "1477824"
  uid: 159ab803-987f-487c-b2c1-96a9f50490e1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      initContainers:
      - name: init-version
        image: busybox:1.28
        command:
          - "sh"
          - "-c"
          - "echo 'Hello from v1' > /usr/share/nginx/html/index.html"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-vol
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-vol
      volumes:
      - name: html-vol
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-10-30T13:16:05Z"
    lastUpdateTime: "2025-10-30T13:16:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-30T13:15:57Z"
    lastUpdateTime: "2025-10-30T13:17:51Z"
    message: ReplicaSet "nginxv1-565dbb69c8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
