apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod-request
  name: nginx-pod-request
  namespace: limitrange
spec:
  containers:
  - image: nginx
    name: nginx-pod-request
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "250Mi"
      limits:
        memory: "500Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
