apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: pi
spec:
  activeDeadlineSeconds: 30
  completions: 5
  parallelism: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo 'hello'; sleep 30; echo 'world'
        image: busybox
        name: pi
        resources: {}
      restartPolicy: Never
status: {}
