apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy
  name: busy
spec:
  containers:
  - command:
    - env
    image: busybox
    name: busy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
