apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-with-pvc
  name: busy-with-pvc
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: busy-with-pvc
    resources: {}
    volumeMounts:
      - mountPath: "/etc/foo"
        name: myvol
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mypvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
