apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-probe
  name: nginx-probe
spec:
  containers:
  - image: nginx
    name: nginx-probe
    resources: {}
    livenessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
