apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrole-bind
subjects:
- kind: ServiceAccount
  name: serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: secrole
  apiGroup: rbac.authorization.k8s.io
