apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-probe
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    readinessProbe:
      httpGet:
        path: /
        port: 80
    livenessProbe:
      exec:
        command:
        - ls /jehee
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
