apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret2 
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/foo"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
