apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-pv2
  name: busy-pv2
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: busy-pv2
    resources: {}
    volumeMounts:
      - mountPath: "/etc/foo"
        name: mypv
  volumes:
    - name: mypv
      persistentVolumeClaim:
        claimName: mypvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
