apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy2
  name: busy2
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: busy2a
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: shared-vol
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: busy2b
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: shared-vol
  volumes:
  - name: shared-vol
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
