apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-pod2
  namespace: mynamespace
spec:
  containers:
  - image: nginx
    name: nginx-pod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
