apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-08-01T13:35:45Z"
  generation: 2
  labels:
    app: try1
  name: try1
  namespace: default
  resourceVersion: "333211"
  uid: db957fe2-aae9-42cf-ab99-c2ec6de9be80
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: try1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: try1
    spec:
      containers:
      - image: 10.97.40.62:5000/simpleapp
        volumeMounts:
          - name: car-vol
            mountPath: /etc/cars
          - name: nfs-vol
            mountPath: /opt
        env:
        - name: ilike
          valueFrom:
            configMapKeyRef:
              name: colors
              key: favorite
        envFrom:
          - configMapRef:
              name: colors
        imagePullPolicy: Always
        name: simpleapp
        readinessProbe:
          periodSeconds: 5
          exec:
            command:
              - ls
              - /etc/cars
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: goproxy
        image: registry.k8s.io/goproxy:0.1
        ports:
          - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: car-vol
        configMap:
          defaultMode: 420
          name: fast-car
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: pvc-one
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 6
  conditions:
  - lastTransitionTime: "2025-08-01T13:36:33Z"
    lastUpdateTime: "2025-08-01T13:36:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-01T13:35:45Z"
    lastUpdateTime: "2025-08-01T13:36:33Z"
    message: ReplicaSet "try1-5d5f55679b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 6
  replicas: 6
  updatedReplicas: 6
