apiVersion: v1
kind: Pod
metadata:
  name: probes-exec
  labels:
    test: probes
spec:
  containers:
  - name: busy
    image: busybox
    imagePullPolicy: Always
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      periodSeconds: 5
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15  # to allow readinessProbe to succeed first
      periodSeconds: 20 
