apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-multi
  name: busy-multi
spec:
  containers:
  - command:
    - sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busy1
  - command:
    - sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busy2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
