apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - port: 80
      protocol: TCP
    # - ipBlock:
    #     cidr: 203.0.113.5/32  
    # # /32 = only this single IP; make ip of nginx webserver container (ip a) 
  # - Egress
